[package]
name = "whistle"
version = "0.1.0"
authors = ["Filippo Rossi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
whistle_core = { path = "../core/" }
whistle_engine = { path = "../engine/" }
clap = "2.33"
# structopt = "0.3.13"
# failure = "0.1.7"
# exitfailure = "0.5.1"
